"""Generate strictly-typed GrowthBook client subclasses from a features JSON.

Python's answer to the JS SDK's ``GrowthBook<AppFeatures>`` + the CLI's
``growthbook features generate-types``: the language has no ``keyof``/indexed
access types, so per-feature key and value checking is delivered via generated
``Literal``-keyed ``@overload`` signatures instead.

Usage:

    python -m growthbook.codegen --input features.json --output growthbook_features.py

``features.json`` is either the SDK endpoint payload (the object containing a
top-level ``"features"`` key) or a bare ``{feature_key: definition}`` map.
Value types are inferred from each feature's ``defaultValue``.

The generated module defines ``TypedGrowthBook`` / ``TypedGrowthBookClient``
subclasses whose typed signatures exist only under ``TYPE_CHECKING`` — at
runtime they inherit everything unchanged. Feature-key typos and wrong
fallback types become checker errors, exactly like the JS "Strict Typing"
tier; runtime behavior is identical to the plain clients.
"""

import argparse
import json
import sys
from typing import Any, Dict, List, Optional

_HEADER_TEMPLATE = '''"""GrowthBook typed client — auto-generated by ``python -m growthbook.codegen``.

DO NOT EDIT. Regenerate from your features JSON instead.
"""

from typing import {typing_imports}

from growthbook import FeatureResult, GrowthBook, GrowthBookClient, UserContext

'''


def python_type_for(default_value: Any) -> str:
    """Map a feature's defaultValue to a Python type expression.

    Mirrors the JS CLI's valueType mapping (boolean/string/number/json);
    ``bool`` is checked before ``int`` because it is an ``int`` subclass.
    """
    if isinstance(default_value, bool):
        return "bool"
    if isinstance(default_value, int):
        return "int"
    if isinstance(default_value, float):
        return "float"
    if isinstance(default_value, str):
        return "str"
    if isinstance(default_value, list):
        return "List[Any]"
    if isinstance(default_value, dict):
        return "Dict[str, Any]"
    return "Any"


def extract_feature_types(payload: Dict[str, Any]) -> Dict[str, str]:
    """Return {feature_key: python_type} from an endpoint payload or bare map."""
    features = payload.get("features", payload)
    if not isinstance(features, dict):
        raise ValueError("features JSON must be an object")
    types: Dict[str, str] = {}
    for key, definition in features.items():
        default_value = definition.get("defaultValue") if isinstance(definition, dict) else None
        types[key] = python_type_for(default_value)
    return dict(sorted(types.items()))


def _client_class(feature_types: Dict[str, str], is_async: bool) -> str:
    name = "TypedGrowthBookClient" if is_async else "TypedGrowthBook"
    base = "GrowthBookClient" if is_async else "GrowthBook"
    prefix = "async " if is_async else ""
    ctx = ", user_context: UserContext" if is_async else ""
    lines = [
        f"class {name}({base}):",
        f'    """{base} with strictly-typed feature keys (checker-only, runtime no-op)."""',
        "",
        "    if TYPE_CHECKING:",
    ]
    items = list(feature_types.items())
    if len(items) == 1:
        # PEP 484 requires at least two @overload declarations, so a single
        # feature gets a plain typed method instead.
        key, py_type = items[0]
        lines += [
            f"        {prefix}def get_feature_value(self, key: Literal[{key!r}], fallback: {py_type}{ctx}) -> {py_type}:  # type: ignore[override]",
            "            raise NotImplementedError",
        ]
    else:
        for i, (key, py_type) in enumerate(items):
            # The Literal-key override is intentionally narrower than the base
            # class signature; checkers report that on the first @overload line.
            marker = "  # type: ignore[override]" if i == 0 else ""
            lines += [
                f"        @overload{marker}",
                f"        {prefix}def get_feature_value(self, key: Literal[{key!r}], fallback: {py_type}{ctx}) -> {py_type}: ...",
            ]
        lines += [
            f"        {prefix}def get_feature_value(self, key: Any, fallback: Any{ctx}) -> Any:",
            "            raise NotImplementedError",
        ]
    lines += [
        "",
        f"        {prefix}def is_on(self, key: FeatureKey{ctx}) -> bool:  # type: ignore[override]",
        "            raise NotImplementedError",
        "",
        f"        {prefix}def is_off(self, key: FeatureKey{ctx}) -> bool:  # type: ignore[override]",
        "            raise NotImplementedError",
        "",
        f'        {prefix}def eval_feature(self, key: FeatureKey{ctx}) -> "FeatureResult[Any]":  # type: ignore[override]',
        "            raise NotImplementedError",
    ]
    return "\n".join(lines)


def generate(payload: Dict[str, Any]) -> str:
    """Generate the typed-client module source from a features payload."""
    feature_types = extract_feature_types(payload)
    if not feature_types:
        raise ValueError("no features found in input JSON")
    typing_imports = ["TYPE_CHECKING", "Any"]
    if any("Dict[" in t for t in feature_types.values()):
        typing_imports.append("Dict")
    if any("List[" in t for t in feature_types.values()):
        typing_imports.append("List")
    typing_imports.append("Literal")
    if len(feature_types) > 1:
        typing_imports.append("overload")
    header = _HEADER_TEMPLATE.format(typing_imports=", ".join(typing_imports))
    key_literals = ", ".join(repr(k) for k in feature_types)
    parts = [
        header,
        f"FeatureKey = Literal[{key_literals}]",
        "",
        "",
        _client_class(feature_types, is_async=False),
        "",
        "",
        _client_class(feature_types, is_async=True),
        "",
    ]
    return "\n".join(parts)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m growthbook.codegen",
        description="Generate strictly-typed GrowthBook clients from a features JSON.",
    )
    parser.add_argument("--input", "-i", required=True, help="features JSON file, or - for stdin")
    parser.add_argument("--output", "-o", default="-", help="output .py file (default: stdout)")
    args = parser.parse_args(argv)

    if args.input == "-":
        payload = json.load(sys.stdin)
    else:
        with open(args.input, encoding="utf-8") as f:
            payload = json.load(f)

    source = generate(payload)

    if args.output == "-":
        sys.stdout.write(source)
    else:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(source)
        print(f"Wrote {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
