"""Generate strictly-typed GrowthBook client subclasses from a features JSON.

Python's answer to the JS SDK's ``GrowthBook<AppFeatures>`` + the CLI's
``growthbook features generate-types``: the language has no ``keyof``/indexed
access types, so per-feature key and value checking is delivered via generated
``Literal``-keyed ``@overload`` signatures instead.

Usage:

    python -m growthbook.codegen --input features.json --output growthbook_features.py

``features.json`` is either the SDK endpoint payload (the object containing a
top-level ``"features"`` key) or a bare ``{feature_key: definition}`` map.
Value types are inferred from each feature's ``defaultValue``.

The generated module defines ``TypedGrowthBook`` / ``TypedGrowthBookClient``
subclasses whose typed signatures exist only under ``TYPE_CHECKING`` — at
runtime they inherit everything unchanged. Feature-key typos and wrong
fallback types become checker errors, exactly like the JS "Strict Typing"
tier; runtime behavior is identical to the plain clients.
"""

import argparse
import json
import sys
from typing import Any, Dict, List, Optional

_HEADER_TEMPLATE = '''"""GrowthBook typed client — auto-generated by ``python -m growthbook.codegen``.

DO NOT EDIT. Regenerate from your features JSON instead.
"""

from typing import {typing_imports}

from growthbook import FeatureResult, GrowthBook, GrowthBookClient, TrackingBuffer, UserContext

'''


def python_type_for(default_value: Any) -> str:
    """Map a feature's defaultValue to a Python type expression.

    Mirrors the JS CLI's valueType mapping (boolean/string/number/json);
    ``bool`` is checked before ``int`` because it is an ``int`` subclass.
    GrowthBook numbers are JS numbers: a feature whose defaultValue happens
    to be an integer may still serve decimal rule values, so int and float
    map to one ``Union[int, float]`` type rather than whichever the snapshot
    contained.
    """
    if isinstance(default_value, bool):
        return "bool"
    if isinstance(default_value, (int, float)):
        return "Union[int, float]"
    if isinstance(default_value, str):
        return "str"
    if isinstance(default_value, list):
        return "List[Any]"
    if isinstance(default_value, dict):
        return "Dict[str, Any]"
    return "Any"


# Top-level keys the SDK endpoint response may carry. Used to distinguish the
# endpoint payload from a bare {feature_key: definition} map that happens to
# contain a feature literally named "features".
_ENDPOINT_KEYS = frozenset(
    {
        "features",
        "savedGroups",
        "contextualBandits",
        "encryptedFeatures",
        "encryptedSavedGroups",
        "encryptedContextualBandits",
        "dateUpdated",
        "status",
    }
)


def _is_endpoint_payload(payload: Dict[str, Any]) -> bool:
    """Structural check: endpoint payloads only have known top-level keys, and
    their "features" value maps feature keys to definition objects."""
    if "features" not in payload or not set(payload) <= _ENDPOINT_KEYS:
        return False
    features = payload["features"]
    if not isinstance(features, dict):
        # Malformed endpoint payload; classify as one so validation raises.
        return True
    return all(isinstance(definition, dict) for definition in features.values())


def infer_feature_type(definition: Any) -> str:
    """Infer a feature's value type from its definition.

    Prefers ``defaultValue``; when that is absent or null, falls back to the
    rules' ``force`` and ``variations`` values (a feature served only by rules
    still has a real value type). Mixed candidate types degrade to ``Any``.
    """
    if not isinstance(definition, dict):
        return "Any"
    candidates: List[Any] = [definition.get("defaultValue")]
    for rule in definition.get("rules") or []:
        if isinstance(rule, dict):
            candidates.append(rule.get("force"))
            # Contextual bandit rules carry their values under
            # contextualVariations instead of variations.
            for key in ("variations", "contextualVariations"):
                variations = rule.get(key)
                if isinstance(variations, list):
                    candidates.extend(variations)
    types = {python_type_for(v) for v in candidates if v is not None}
    if len(types) == 1:
        return types.pop()
    return "Any"


def extract_feature_types(
    payload: Dict[str, Any], payload_format: str = "auto"
) -> Dict[str, str]:
    """Return {feature_key: python_type} from an endpoint payload or bare map.

    ``payload_format`` is "auto" (structural detection), "payload" (force
    endpoint-payload interpretation), or "map" (force bare-map interpretation
    — needed for the ambiguous corner of a bare map whose only feature is
    named "features").
    """
    if payload_format not in ("auto", "payload", "map"):
        raise ValueError(f"unknown payload_format: {payload_format!r}")
    if payload_format != "map" and "encryptedFeatures" in payload and "features" not in payload:
        # Without this check the encrypted blob's sibling keys (status,
        # dateUpdated, ...) would be emitted as fake Any-typed feature keys.
        raise ValueError(
            "payload contains encryptedFeatures but no plaintext features: "
            "decrypt it first (pass --decryption-key to the CLI)"
        )
    if payload_format == "payload" or (
        payload_format == "auto" and _is_endpoint_payload(payload)
    ):
        features = payload.get("features", {})
    else:
        features = payload
    if not isinstance(features, dict):
        raise ValueError("features JSON must be an object")
    types: Dict[str, str] = {}
    for key, definition in features.items():
        types[key] = infer_feature_type(definition)
    return dict(sorted(types.items()))


def _client_class(feature_types: Dict[str, str], is_async: bool) -> str:
    name = "TypedGrowthBookClient" if is_async else "TypedGrowthBook"
    base = "GrowthBookClient" if is_async else "GrowthBook"
    prefix = "async " if is_async else ""
    # The async overrides must stay signature-compatible with GrowthBookClient,
    # whose eval methods take a keyword-only per-request tracking_buffer.
    ctx = (
        ", user_context: UserContext, *, tracking_buffer: Optional[TrackingBuffer] = None"
        if is_async
        else ""
    )
    lines = [
        f"class {name}({base}):",
        f'    """{base} with strictly-typed feature keys (checker-only, runtime no-op)."""',
        "",
        "    if TYPE_CHECKING:",
    ]
    items = list(feature_types.items())

    # get_feature_value: per key, a `fallback: None -> Optional[T]` overload
    # ("no fallback, give me the value if set") plus the typed-fallback one.
    # An Any-typed key gets a single `fallback: Any` overload (it already
    # accepts None), so a lone Any-typed feature keeps the plain-method form
    # (PEP 484 requires at least two @overload declarations).
    gfv_signatures = []
    for key, py_type in items:
        if py_type != "Any":
            gfv_signatures.append((key, "None", f"Optional[{py_type}]"))
        gfv_signatures.append((key, py_type, py_type))
    if len(gfv_signatures) == 1:
        key, fb_type, ret_type = gfv_signatures[0]
        lines += [
            f"        {prefix}def get_feature_value(self, key: Literal[{key!r}], fallback: {fb_type}{ctx}) -> {ret_type}:  # type: ignore[override]",
            "            raise NotImplementedError",
        ]
    else:
        for i, (key, fb_type, ret_type) in enumerate(gfv_signatures):
            # The Literal-key override is intentionally narrower than the base
            # class signature; checkers report that on the first @overload line.
            marker = "  # type: ignore[override]" if i == 0 else ""
            lines += [
                f"        @overload{marker}",
                f"        {prefix}def get_feature_value(self, key: Literal[{key!r}], fallback: {fb_type}{ctx}) -> {ret_type}: ...",
            ]
        lines += [
            f"        {prefix}def get_feature_value(self, key: Any, fallback: Any{ctx}) -> Any:",
            "            raise NotImplementedError",
        ]

    # eval_feature: per-key FeatureResult[T] overloads — result.value is
    # Optional[T] instead of Any.
    lines += [""]
    if len(items) == 1:
        key, py_type = items[0]
        lines += [
            f'        {prefix}def eval_feature(self, key: Literal[{key!r}]{ctx}) -> "FeatureResult[{py_type}]":  # type: ignore[override]',
            "            raise NotImplementedError",
        ]
    else:
        for i, (key, py_type) in enumerate(items):
            marker = "  # type: ignore[override]" if i == 0 else ""
            lines += [
                f"        @overload{marker}",
                f'        {prefix}def eval_feature(self, key: Literal[{key!r}]{ctx}) -> "FeatureResult[{py_type}]": ...',
            ]
        lines += [
            f'        {prefix}def eval_feature(self, key: Any{ctx}) -> "FeatureResult[Any]":',
            "            raise NotImplementedError",
        ]

    lines += [
        "",
        f"        {prefix}def is_on(self, key: FeatureKey{ctx}) -> bool:  # type: ignore[override]",
        "            raise NotImplementedError",
        "",
        f"        {prefix}def is_off(self, key: FeatureKey{ctx}) -> bool:  # type: ignore[override]",
        "            raise NotImplementedError",
    ]
    return "\n".join(lines)


def decrypt_payload(payload: Dict[str, Any], decryption_key: str) -> Dict[str, Any]:
    """Return a copy of an encrypted endpoint payload with ``encryptedFeatures``
    decrypted into a plaintext ``features`` object."""
    encrypted = payload.get("encryptedFeatures")
    if not encrypted:
        raise ValueError("a decryption key was given but the payload has no encryptedFeatures")
    from .growthbook import decrypt

    out = {k: v for k, v in payload.items() if k != "encryptedFeatures"}
    out["features"] = json.loads(decrypt(encrypted, decryption_key))
    return out


def generate(payload: Dict[str, Any], payload_format: str = "auto") -> str:
    """Generate the typed-client module source from a features payload."""
    feature_types = extract_feature_types(payload, payload_format)
    if not feature_types:
        raise ValueError("no features found in input JSON")
    degraded = sorted(k for k, t in feature_types.items() if t == "Any")
    if degraded:
        # These keys LOOK typed in the generated client but carry no value
        # contract — make that visible at generation time.
        print(
            "warning: no value type could be inferred for feature(s) "
            f"{', '.join(degraded)}; they are typed Any in the generated client",
            file=sys.stderr,
        )
    typed_count = sum(1 for t in feature_types.values() if t != "Any")
    typing_imports = ["TYPE_CHECKING", "Any"]
    if any("Dict[" in t for t in feature_types.values()):
        typing_imports.append("Dict")
    if any("List[" in t for t in feature_types.values()):
        typing_imports.append("List")
    typing_imports.append("Literal")
    # Always needed: the async overrides' tracking_buffer is Optional.
    typing_imports.append("Optional")
    if any("Union[" in t for t in feature_types.values()):
        typing_imports.append("Union")
    # Overloads are emitted whenever get_feature_value or eval_feature has
    # more than one signature (see _client_class).
    if len(feature_types) > 1 or typed_count:
        typing_imports.append("overload")
    header = _HEADER_TEMPLATE.format(typing_imports=", ".join(typing_imports))
    key_literals = ", ".join(repr(k) for k in feature_types)
    parts = [
        header,
        f"FeatureKey = Literal[{key_literals}]",
        "",
        "",
        _client_class(feature_types, is_async=False),
        "",
        "",
        _client_class(feature_types, is_async=True),
        "",
    ]
    return "\n".join(parts)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m growthbook.codegen",
        description="Generate strictly-typed GrowthBook clients from a features JSON.",
    )
    parser.add_argument("--input", "-i", required=True, help="features JSON file, or - for stdin")
    parser.add_argument("--output", "-o", default="-", help="output .py file (default: stdout)")
    parser.add_argument(
        "--format",
        choices=["auto", "payload", "map"],
        default="auto",
        dest="payload_format",
        help="input shape: SDK endpoint payload, bare {feature_key: definition} map, "
        "or auto-detect (default)",
    )
    parser.add_argument(
        "--decryption-key",
        default=None,
        help="decrypt the payload's encryptedFeatures before generating "
        "(for endpoints with encryption enabled)",
    )
    args = parser.parse_args(argv)

    if args.input == "-":
        payload = json.load(sys.stdin)
    else:
        with open(args.input, encoding="utf-8") as f:
            payload = json.load(f)

    if args.decryption_key:
        payload = decrypt_payload(payload, args.decryption_key)

    source = generate(payload, args.payload_format)

    if args.output == "-":
        sys.stdout.write(source)
    else:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(source)
        print(f"Wrote {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
