"""Generate strictly-typed GrowthBook client subclasses from a features JSON.

Python's answer to the JS SDK's ``GrowthBook<AppFeatures>`` + the CLI's
``growthbook features generate-types``: the language has no ``keyof``/indexed
access types, so per-feature key and value checking is delivered via generated
``Literal``-keyed ``@overload`` signatures instead.

Usage:

    python -m growthbook.codegen --input features.json --output growthbook_features.py

``features.json`` is either the SDK endpoint payload (the object containing a
top-level ``"features"`` key) or a bare ``{feature_key: definition}`` map.
Value types are inferred from each feature's ``defaultValue``.

The generated module defines ``TypedGrowthBook`` / ``TypedGrowthBookClient``
subclasses whose typed signatures exist only under ``TYPE_CHECKING`` — at
runtime they inherit everything unchanged. Feature-key typos and wrong
fallback types become checker errors, exactly like the JS "Strict Typing"
tier; runtime behavior is identical to the plain clients.
"""

import argparse
import json
import sys
from typing import Any, Dict, List, Optional

_HEADER = '''"""GrowthBook typed client — auto-generated by ``python -m growthbook.codegen``.

DO NOT EDIT. Regenerate from your features JSON instead.
"""

from typing import TYPE_CHECKING, Any, Dict, List, Literal, overload

from growthbook import FeatureResult, GrowthBook, GrowthBookClient, UserContext

'''


def python_type_for(default_value: Any) -> str:
    """Map a feature's defaultValue to a Python type expression.

    Mirrors the JS CLI's valueType mapping (boolean/string/number/json);
    ``bool`` is checked before ``int`` because it is an ``int`` subclass.
    """
    if isinstance(default_value, bool):
        return "bool"
    if isinstance(default_value, int):
        return "int"
    if isinstance(default_value, float):
        return "float"
    if isinstance(default_value, str):
        return "str"
    if isinstance(default_value, list):
        return "List[Any]"
    if isinstance(default_value, dict):
        return "Dict[str, Any]"
    return "Any"


def extract_feature_types(payload: Dict[str, Any]) -> Dict[str, str]:
    """Return {feature_key: python_type} from an endpoint payload or bare map."""
    features = payload.get("features", payload)
    if not isinstance(features, dict):
        raise ValueError("features JSON must be an object")
    types: Dict[str, str] = {}
    for key, definition in features.items():
        default_value = definition.get("defaultValue") if isinstance(definition, dict) else None
        types[key] = python_type_for(default_value)
    return dict(sorted(types.items()))


def _sync_class(feature_types: Dict[str, str]) -> str:
    lines = [
        "class TypedGrowthBook(GrowthBook):",
        '    """GrowthBook with strictly-typed feature keys (checker-only, runtime no-op)."""',
        "",
        "    if TYPE_CHECKING:",
    ]
    for i, (key, py_type) in enumerate(feature_types.items()):
        # The Literal-key override is intentionally narrower than the base
        # class signature; mypy reports that on the first @overload line.
        marker = "  # type: ignore[override]" if i == 0 else ""
        lines += [
            f"        @overload{marker}",
            f"        def get_feature_value(self, key: Literal[{key!r}], fallback: {py_type}) -> {py_type}: ...",
        ]
    lines += [
        "        def get_feature_value(self, key: Any, fallback: Any) -> Any:",
        "            raise NotImplementedError",
        "",
        "        def is_on(self, key: FeatureKey) -> bool:  # type: ignore[override]",
        "            raise NotImplementedError",
        "",
        "        def is_off(self, key: FeatureKey) -> bool:  # type: ignore[override]",
        "            raise NotImplementedError",
        "",
        '        def eval_feature(self, key: FeatureKey) -> "FeatureResult[Any]":  # type: ignore[override]',
        "            raise NotImplementedError",
    ]
    return "\n".join(lines)


def _async_class(feature_types: Dict[str, str]) -> str:
    lines = [
        "class TypedGrowthBookClient(GrowthBookClient):",
        '    """GrowthBookClient with strictly-typed feature keys (checker-only, runtime no-op)."""',
        "",
        "    if TYPE_CHECKING:",
    ]
    for i, (key, py_type) in enumerate(feature_types.items()):
        marker = "  # type: ignore[override]" if i == 0 else ""
        lines += [
            f"        @overload{marker}",
            f"        async def get_feature_value(self, key: Literal[{key!r}], fallback: {py_type}, user_context: UserContext) -> {py_type}: ...",
        ]
    lines += [
        "        async def get_feature_value(self, key: Any, fallback: Any, user_context: UserContext) -> Any:",
        "            raise NotImplementedError",
        "",
        "        async def is_on(self, key: FeatureKey, user_context: UserContext) -> bool:  # type: ignore[override]",
        "            raise NotImplementedError",
        "",
        "        async def is_off(self, key: FeatureKey, user_context: UserContext) -> bool:  # type: ignore[override]",
        "            raise NotImplementedError",
        "",
        '        async def eval_feature(self, key: FeatureKey, user_context: UserContext) -> "FeatureResult[Any]":  # type: ignore[override]',
        "            raise NotImplementedError",
    ]
    return "\n".join(lines)


def generate(payload: Dict[str, Any]) -> str:
    """Generate the typed-client module source from a features payload."""
    feature_types = extract_feature_types(payload)
    if not feature_types:
        raise ValueError("no features found in input JSON")
    key_literals = ", ".join(repr(k) for k in feature_types)
    parts = [
        _HEADER,
        f"FeatureKey = Literal[{key_literals}]",
        "",
        "",
        _sync_class(feature_types),
        "",
        "",
        _async_class(feature_types),
        "",
    ]
    return "\n".join(parts)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m growthbook.codegen",
        description="Generate strictly-typed GrowthBook clients from a features JSON.",
    )
    parser.add_argument("--input", "-i", required=True, help="features JSON file, or - for stdin")
    parser.add_argument("--output", "-o", default="-", help="output .py file (default: stdout)")
    args = parser.parse_args(argv)

    if args.input == "-":
        payload = json.load(sys.stdin)
    else:
        with open(args.input, encoding="utf-8") as f:
            payload = json.load(f)

    source = generate(payload)

    if args.output == "-":
        sys.stdout.write(source)
    else:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(source)
        print(f"Wrote {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
