"""GrowthBook typed client — auto-generated by ``python -m growthbook.codegen``.

DO NOT EDIT. Regenerate from your features JSON instead.
"""

from typing import TYPE_CHECKING, Any, Dict, List, Literal, overload

from growthbook import FeatureResult, GrowthBook, GrowthBookClient, UserContext


FeatureKey = Literal['banner_text', 'dark_mode', 'donut_price', 'max_items', 'meal_overrides']


class TypedGrowthBook(GrowthBook):
    """GrowthBook with strictly-typed feature keys (checker-only, runtime no-op)."""

    if TYPE_CHECKING:
        @overload  # type: ignore[override]
        def get_feature_value(self, key: Literal['banner_text'], fallback: str) -> str: ...
        @overload
        def get_feature_value(self, key: Literal['dark_mode'], fallback: bool) -> bool: ...
        @overload
        def get_feature_value(self, key: Literal['donut_price'], fallback: float) -> float: ...
        @overload
        def get_feature_value(self, key: Literal['max_items'], fallback: int) -> int: ...
        @overload
        def get_feature_value(self, key: Literal['meal_overrides'], fallback: Dict[str, Any]) -> Dict[str, Any]: ...
        def get_feature_value(self, key: Any, fallback: Any) -> Any:
            raise NotImplementedError

        def is_on(self, key: FeatureKey) -> bool:  # type: ignore[override]
            raise NotImplementedError

        def is_off(self, key: FeatureKey) -> bool:  # type: ignore[override]
            raise NotImplementedError

        def eval_feature(self, key: FeatureKey) -> "FeatureResult[Any]":  # type: ignore[override]
            raise NotImplementedError


class TypedGrowthBookClient(GrowthBookClient):
    """GrowthBookClient with strictly-typed feature keys (checker-only, runtime no-op)."""

    if TYPE_CHECKING:
        @overload  # type: ignore[override]
        async def get_feature_value(self, key: Literal['banner_text'], fallback: str, user_context: UserContext) -> str: ...
        @overload
        async def get_feature_value(self, key: Literal['dark_mode'], fallback: bool, user_context: UserContext) -> bool: ...
        @overload
        async def get_feature_value(self, key: Literal['donut_price'], fallback: float, user_context: UserContext) -> float: ...
        @overload
        async def get_feature_value(self, key: Literal['max_items'], fallback: int, user_context: UserContext) -> int: ...
        @overload
        async def get_feature_value(self, key: Literal['meal_overrides'], fallback: Dict[str, Any], user_context: UserContext) -> Dict[str, Any]: ...
        async def get_feature_value(self, key: Any, fallback: Any, user_context: UserContext) -> Any:
            raise NotImplementedError

        async def is_on(self, key: FeatureKey, user_context: UserContext) -> bool:  # type: ignore[override]
            raise NotImplementedError

        async def is_off(self, key: FeatureKey, user_context: UserContext) -> bool:  # type: ignore[override]
            raise NotImplementedError

        async def eval_feature(self, key: FeatureKey, user_context: UserContext) -> "FeatureResult[Any]":  # type: ignore[override]
            raise NotImplementedError
